font:
  normal:
    family: Source Code Pro for Powerline
  # bold:
  #   family: Roboto Mono Bold for Powerline
  # italic:
  #   family: Roboto Mono Italic for Powerline
  # bold_italic:
  #   family: Roboto Mono Bold Italic for Powerline
  size: 9

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"
