#+TITLE: Dotfiles

My dotfiles, managed using the [[https://www.gnu.org/software/stow/][GNU Stow]] symlink farm manager.

* Table of contents                                            :toc_1:noexport:
- [[#about-gnu-stow][About GNU Stow]]
- [[#packages][Packages]]
- [[#todos][TODOs]]

* About GNU Stow

You can read a short GNU Stow tutorial in my notes, [[https://github.com/alecigne/notes/blob/master/stow.org][here on GitHub]] or
[[https://anthony.lecigne.net/stow.html][on my website]].

* Packages

** cmus

[[https://cmus.github.io][cmus]] is a small, fast and powerful console music player for Unix-like
operating systems.

** Common Lisp

My Common Lisp (SBCL) configuration.

*** ASDF

[[https://common-lisp.net/project/asdf/][Another System Definition Facility]], a build system for Common Lisp.

This includes the configuration for ASDF's ~source-registry~. More
info [[https://common-lisp.net/project/asdf/asdf/Configuring-ASDF-to-find-your-systems.html][here]].

*** SBCL

[[http://www.sbcl.org/][SBCL]], a high performance Common Lisp compiler.

** cVim

[[https://chrome.google.com/webstore/detail/cvim/ihlenndgcmojhcghmfjfneahoeklbjjh][cVim]], an extension adding Vim-like bindings to Google Chrome.

Just load this once in Chrome:

#+begin_example
  set localconfig
  let configpath = '/path/to/.cvimrc'
#+end_example

** Emacs

[[https://github.com/alecigne/.emacs.d][SwanEmacs]], my Org-based Emacs configuration, included as a submodule.

** Fonts

- [[https://github.com/adobe-fonts/source-code-pro][Source Code Pro]]
- [[https://github.com/FortAwesome/Font-Awesome][FontAwesome]]

** Git

My [[https://git-scm.com/][Git]] configuration. So far it only includes a selection of ~git~
aliases from the [[https://github.com/GitAlias/gitalias][gitalias]] repository, organized with ~org-babel~ for
more readability. Please go to the original source for reference.

*** Usage

**** Org

- Every section has a Noweb reference.

- Everything is then fed to a main code block through Noweb (see
  the bottom of the raw Org file).

- The result after ~org-babel-tangle~ is a ~.gitalias~ file.

**** Git

Add this to ~.gitconfig~ after generating ~.gitalias~ and stowing:

#+BEGIN_EXAMPLE
  [include]
  path = .gitalias
#+END_EXAMPLE

** GnuPG

My [[https://www.gnupg.org/][GnuPG]] config files.

** i3

My config for the [[https://i3wm.org/][i3]] window manager, including my [[https://i3wm.org/i3status/manpage.html][i3status]]
configuration.

** Packages

My installed packages, a work in progress.

** Polybar

[[https://github.com/polybar/polybar][Polybar]], a fast and easy-to-use status bar.

** Rofi

[[https://github.com/davatorium/rofi][Rofi]], a window switcher, application launcher and dmenu replacement.

** StumpWM

My [[https://github.com/alecigne/.stumpwm.d][StumpWM config]], included as a submodule.

** Wallpapers

Good resources:

- https://wallhaven.cc/
- https://unsplash.com/

** Xmodmap

My Xmodmap config.

** Zsh

A great [[http://www.zsh.org/][shell]].

* TODOs

- [X] Add fonts
